# Adam parameters
beta1: 0.9
beta2: 0.999
epsilon: 1e-6

# hyperparameters
init_learning_rate: 0.0005
batch_size: 128
epochs: 100  # not sure what it is.
decay: 0
dampening: 0

# system parameters
log_interval: 100
seed: 1
best_model: best_model.pth